linters:
  Comment:
    enabled: false
  IdWithExtraneousSelector:
    enabled: false
  Indentation:
    enabled: false
  SelectorDepth:
    max_depth: 4
  SelectorFormat:
    ignored_names: [ disqus_thread ]
