linters:
  Comment:
    enabled: false
  DuplicateProperty:
    enabled: false # necessary for fallback properties, like font-size (px and rem) and height (px and vh)
  Indentation:
    enabled: false
  SelectorDepth:
    max_depth: 4
  SelectorFormat:
    ignored_names: [ disqus_thread ]
